---
abstract: 'Functions to validate data types in test files.'
author:
  - 'Guillaume Aubert <aubertg@cpan.org>'
build_requires:
  File::Spec: 0
  Test::Builder::Tester: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Type
provides:
  Test::Type:
    file: lib/Test/Type.pm
    version: v1.1.1
requires:
  Carp: 0
  Data::Validate::Type: 1.002000
  Exporter: 5.57
  Test::More: 0.94
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/NoAuth/ReportBug.html?Queue=test-type
  homepage: https://metacpan.org/release/Test-Type
  license: http://www.gnu.org/licenses/gpl-3.0.txt
  repository: https://github.com/guillaumeaubert/Test-Type
version: v1.1.1
